-- 1) Create the response table
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  nickname text,
  answers jsonb not null,
  other_text jsonb,
  submitted_at timestamptz not null default now()
);

-- 2) Enable Row Level Security
alter table public.survey_responses enable row level security;

-- 3) Public visitors may submit answers, but cannot read them.
grant insert on table public.survey_responses to anon;

drop policy if exists "Anyone can submit survey responses" on public.survey_responses;
create policy "Anyone can submit survey responses"
on public.survey_responses
for insert
to anon
with check (true);

-- IMPORTANT: Do NOT create a SELECT policy for anon.
-- You can review/export responses from the Supabase dashboard while the table remains private to visitors.
